name: deer-test-java-spring

on:
  workflow_call:
    inputs:
      module:
        required: false # module을 지정하지 않으면 전체 모듈에 대해 테스트를 수행한다.
        default: ''
        type: string

jobs:
  build:
    runs-on: self-hosted # 디어 빌드 머신 이용

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: ${{ inputs.module == '' && '' || format(':{0}:', inputs.module) }}check