name: deer-deploy-java-spring

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: zulu
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Test with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: :${{ inputs.application }}:check