# https://github.com/actions/labeler
name: "Pull Request Labeler"

on:
  workflow_call:

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}