name: Sonarqube

on:
  workflow_call:
    inputs:
      install_dependency:
        description: '의존성 설치 커맨드'
        default: 'npm install'
        required: false
        type: string
    secrets:
      SONAR_HOST_URL:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  SonarScanner:
    runs-on: ubuntu-latest
    name: Sonar Scanner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ${{ inputs.install_dependency }}
      - name: Scan code
        uses: vtex/action-sonarqube@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          host: ${{ secrets.SONAR_HOST_URL }} # Variable set in the Github Secrets
          token: ${{ secrets.SONAR_TOKEN }} # Variable set in the Github Secrets